### ISSUE TITLE
启用横屏适配时，退出全屏可能导致评论区消失

### ISSUE THREAD

**Issue by cheeserick** [orz12/pilipala#11]
### 问题描述
如题，设置中勾选横屏适配，如果未触发[全屏不能正常显示的bug](https://github.com/orz12/pilipala/issues/7)，在退出全屏后可能导致评论区消失。

### 复现步骤
1.启用横屏适配
2.打开一个视频
3.打开评论区
4.切换全屏
5.退出全屏（有几率触发）

### 预期行为
评论区正常显示

### 错误日志

```
PiliPalaX错误日志 
 ********************
------- 设备信息 -------
id: 58.2.A.10.126
============bootloader: xboot
brand: Sony
device: XQ-AS72
display: 58.2.A.10.126
fingerprint: Sony/XQ-AS72/XQ-AS72:12/58.2.A.10.126/058002A010012603718185433:user/releaboard: khardbootloader:host: Bbrand: SoisPdevice: XQ-AS72
display: 58.2.A.10.126
fingerprint: Soproduct: XQ-AS72
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 058002A010012603718185433
versionPreviewSdk: 0
versionRelease: 12
versionSdk: 31
versionSecurityPatch: 2022-10-01
------- 应用信息 -------
environment: release
version: 1.0.19
appName: PiliPalaX
buildNumber: 1243
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
type 'RenderErrorBox' is not a subtype of type 'RenderSliver' of 'chiappN
------- 错误堆栈 -------
#0      ContainerRenderObjectMixin.in
---------- 错误信息 ----------
Null check operator used on a null value
------- 错误堆栈 -------
#0      Element.widget (package:flutter/src/widgets/framework.dart:3474)
#1      Element.updateChild (package:flutter/src/widgets/framework.dart:3789)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#7      Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#8      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#9      _ViewportElement.update (package:flutter/src/widgets/viewport.dart:235)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#34     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#41     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#42     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#43     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#47     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#55     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#56     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#57     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#61     StatelessElement.update (package:flutter/src/widgets/framework.dart:5547)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#63     Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#64     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#68     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#72     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#74     Element.updateChildren (package:flutter/src/widgets/framework.dart:3964)
#75     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#78     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#80     StatefulElement.update (package:flutter/src/widgets/framework.dart:5657)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3815)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#85     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#86     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#87     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#88     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#89     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#90     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#91     _invoke (dart:ui/hooks.dart:312)
#92     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#93     _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```
### 相关信息
录屏文件太大，放一个评论区消失的截图。![screen-20240222-014333_exported_30209.jpg](https://github.com/orz12/pilipala/assets/21290026/e2ffcda8-722e-4e42-94a4-c149811e48f2)

**Comment by orz12** [comment]
奇怪 日志怎么中间有一段没了

**Comment by orz12** [comment]
不过能复现出来 症状有点不一样 研究一下

**Comment by VillagerTom** [comment]
日志最好还是用代码块括一下，~~平等地DDoS每一条issue.apng~~

**Comment by cheeserick** [comment]
@VillagerTom 好好好（

**Comment by orz12** [comment]
https://github.com/orz12/pilipala/commit/e78cd8b179352ac6b969c9fc2b22186e199741dd
