### ISSUE TITLE
BUG: 评论底部的白色区域

### ISSUE THREAD

**Issue by lingbopro** [orz12/pilipala#119]
### 问题描述
评论详情页面底部的大片白色区域

### 复现步骤
见下方截图和录屏

### 预期行为
不应有白色区域

### 错误日志
请提供设置->关于->错误日志中的内容，粘贴在下方代码框中。如果没有，请提供您的app版本号、系统版本、设备型号等相关信息。

APP: `1.0.21-beta2+160`  
系统: `HarmonyOS 2 (Android 10)`  
设备: `HWAWEI Mate 20 Pro`  

（错误日志我不确定是不是这个）

<details>

```
PiliPalaX错误日志
********************
------- 设备信息 -------
id: HUAWEIEVR-AL00
board: EVR
bootloader: unknown
brand: HUAWEI
device: HWEVR
display: EVR-AL00 10.1.0.163(C00E160R2P8)
fingerprint: HUAWEI/EVR-AL00/HWEVR:10/HUAWEIEVR-AL00/10.1.0.163C00:user/release-keys
hardware: kirin980
host: cn-central-1b-564e7048f1595385991956-1606187626-f78qj
isPhysicalDevice: true
manufacturer: HUAWEI
model: EVR-AL00
product: EVR-AL00
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: 10.1.0.163C00
versionPreviewSdk: 0
versionRelease: 10
versionSdk: 29
versionSecurityPatch: 2020-07-01
------- 应用信息 -------
environment: release
version: 1.0.21-beta.2
appName: PiliPalaX
buildNumber: 1603
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>
------- CUSTOM INFO -------
```

</details>

### 相关信息
截图:  

![Screenshot_20240704_102415_com.orz12.PiliPalaX.jpg](https://github.com/orz12/pilipala/assets/148617407/9ecc74c6-636e-48d2-ae3f-1f1258a95b15)

录屏:  

https://github.com/orz12/pilipala/assets/148617407/7b68d807-3063-45fd-a84f-870e5ff438f9

BV号: `BV1WV411R7Rk`

**Comment by orz12** [comment]
不是这个日志

**Comment by lingbopro** [comment]
> 不是这个日志

那就没别的日志了

**Comment by orz12** [comment]
修好了 下版本更新
