### ISSUE TITLE
进入播放页面时导致系统界面无响应卡死

### ISSUE THREAD

**Issue by SpaceThing** [orz12/pilipala#18]
### 问题描述
进入播放页面时导致系统界面无响应卡死

无法使用任何手势、退出应用或锁屏，等待一段时间后恢复

### 复现步骤
打开应用，点击任意视频播放
一段时间内只会出现一次卡死

### 错误日志
[log.txt](https://github.com/orz12/pilipala/files/14392229/log.txt)

**Comment by orz12** [comment]
修了一部分日志的错误

**Comment by SpaceThing** [comment]
仍然会出现卡死😭
这个是手快划掉后台后的日志
 ********************
------- 设备信息 -------
id: TKQ1.220905.001
board: taro
bootloader: unknown
brand: Redmi
device: mondrian
display: TKQ1.220905.001 test-keys
fingerprint: Redmi/mondrian/mondrian:13/TKQ1.220905.001/V14.0.24.0.TMNCNXM:user/release-keys
hardware: qcom
host: pangu-build-component-system-103966-t1sfk-h9x9w-nnn08
isPhysicalDevice: true
manufacturer: Xiaomi
model: 23013RK75C
product: mondrian
tags: release-keys
type: user
versionBaseOs: 
versionCodename: REL
versionIncremental: V14.0.24.0.TMNCNXM
versionPreviewSdk: 0
versionRelease: 13
versionSdk: 33
versionSecurityPatch: 2023-04-01
------- 应用信息 -------
environment: release
version: 1.0.20
appName: PiliPalaX
buildNumber: 1503
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
Bad state: Cannot add event after closing
------- 错误堆栈 -------
#0      _StreamController.add (dart:async/stream_controller.dart:605)
#1      Floating.pipStatus$.<anonymous closure> (package:floating/src/floating.dart:56)
<asynchronous suspension>
------- CUSTOM INFO -------

以及另一个多次出现的错误日志
 ********************
------- 应用信息 -------
environment: release
version: 1.0.20
appName: PiliPalaX
buildNumber: 1503
packageName: com.orz12.PiliPalaX
---------- 错误信息 ----------
LateInitializationError: Field 'heroTag' has not been initialized.
------- 错误堆栈 -------
#0      State.widget (package:flutter/src/widgets/framework.dart)
#1      _HeaderControlState.initState (package:PiliPalaX/pages/video/detail/widgets/header_control.dart:65)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#63     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#64     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3831)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#86     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#91     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#92     _invoke (dart:ui/hooks.dart:312)
#93     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#94     _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------

**Comment by orz12** [comment]
系统卡死是硬解的问题 关掉一般就好了

**Comment by SpaceThing** [comment]
ok我试下，谢谢！

**Comment by SpaceThing** [comment]
> 系统卡死是硬解的问题 关掉一般就好了

关掉硬解后刚刚又一次出现了系统卡死，出现在第一次启动app后第一个视频播放，卡死在视频加载，无法进行任何操作，强制重启了没有留下日志
