### ISSUE TITLE
冷启动进入播放界面后有概率卡死

### ISSUE THREAD

**Issue by SpaceThing** [orz12/pilipala#82]
### 问题描述
冷启动进入播放界面后有概率卡死，已经关闭硬解

### 错误日志

不确定日志是否完整正确

```
/widgets/framework.dart:5453)
#15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#37     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6736)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#63     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6871)
#64     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6883)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#76     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
#79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3831)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
#86     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895)
#87     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984)
#88     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457)
#89     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325)
#90     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255)
#91     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113)
#92     _invoke (dart:ui/hooks.dart:312)
#93     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383)
#94     _drawFrame (dart:ui/hooks.dart:283)
------- CUSTOM INFO -------
```

### 截图
![Screenshot_2024-05-13-17-44-19-769_com orz12 PiliPalaX](https://github.com/orz12/pilipala/assets/61451659/ca3dee1d-a649-4722-b77e-8c68bf93fa39)

**Comment by SpaceThing** [comment]
#18

**Comment by xsfx0313** [comment]
> #18 

？
